servlet:
  port: 8080

spring:
  security:
    oauth2:
      client:
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: name
        registration:
          github:
            authorization-grant-type: authorization_code
            client-authentication-method: basic
            client-name: Github Client
            client-id: 申请到的Client ID
            client-secret: 申请到的Client Secret
            provider: github
            redirect-uri-template: 申请填写的Authorization callback URL
            scope: default